Fix mypy presubmit error
Occasionally, the following presubmit error occurs:

https://logs.chromium.org/logs/v8/buildbucket/cr-buildbucket/8695773343458046561/+/u/presubmit/stdout

mypy
vpython3 -m mypy --check-untyped-defs --pretty /b/s/w/ir/cache/builder/Crossbench_Presubmit/s/crossbench PRESUBMIT.py (13.07s) failed
crossbench/pinpoint/job_results.py:11: error: Skipping analyzing
"google.cloud": module is installed, but missing library stubs or py.typed
marker  [import-untyped]
    from google.cloud import storage
    ^

This CL is an attempt to fix the error by importing `google.cloud.storage` in `job_results.py` the same way as `crossbench/plt/base.py` because mypy complains about `google.cloud` but not `google.cloud.storage`.

Change-Id: Ie85078d3d3a0dcd8d72517058fc882347d4169e5
Reviewed-on: https://chromium-review.googlesource.com/c/crossbench/+/7252790
Reviewed-by: Camillo Bruni <cbruni@chromium.org>
Commit-Queue: Maxim Sheshukov <maximsheshukov@google.com>