Fix presubmit error
The presubmit error looks like:
vpython3 -m mypy --check-untyped-defs --pretty /b/s/w/ir/cache/builder/Crossbench_Presubmit/s/crossbench PRESUBMIT.py (7.53s) failed
crossbench/pinpoint/job_results.py:11: error: Skipping analyzing
"google.cloud": module is installed, but missing library stubs or py.typed
marker  [import-untyped]
    import google.cloud.storage as gcloud_storage

This CL makes mypy to follow untyped imports because
google-cloud-storage does not include stubs.

Change-Id: Ia5ff182ea35a5b453f826b7abbcd33b8e42c1581
Reviewed-on: https://chromium-review.googlesource.com/c/crossbench/+/7262238
Reviewed-by: Camillo Bruni <cbruni@chromium.org>
Commit-Queue: Maxim Sheshukov <maximsheshukov@google.com>